class Character():
    def __init__(self):
        self.char_name = ""
        self.char_class = ""
        self.race = ""
        self.background = ""
        self.alignment = ""
        self.player_name = ""
        self.experience = "0"
        self.personality = ""
        self.ideals = ""
        self.bonds = ""
        self.flaws = ""
        self.features = ""
        self.traits = ""
        self.str = ""
        self.dex = ""
        self.const = ""
        self.int = ""
        self.wisdom = ""
        self.charisma = ""
        self.str_modifier = ""
        self.dex_modifier = ""
        self.const_modifier = ""
        self.int_modifier = ""
        self.wisdom_modifier = ""
        self.charisma_modifier = ""
        self.inspiration = ""
        self.passive_wisdom = ""
        self.other_proficiencies = ""
        self.languages = ""
        self.equipment = []
        self.ability_bonuses = []   #strength, dexterity, constitution, intelligence, wisdom, charisma
        self.cp = ""  #copper
        self.sp = ""  #silver
        self.ep = ""  #electrium
        self.gp = ""  #gold
        self.pp = ""  #platinum
        self.proficiency_bonus = ""
        self.str_throw = ""
        self.dex_throw = ""
        self.const_throw = ""
        self.int_throw = ""
        self.wisdom_throw = ""
        self.charisma_throw = ""
        self.prof_save = ['No',]
        self.skills = {}    #{'Acrobatics':'15',...}
        self.prof_skills = {}   #{'Acrobatics': 'Yes', 'Arcana': 'No',...}
        self.prof_misc = []
        self.armor = ""
        self.initiative = ""
        self.speed = ""
        self.HP_max = ""
        self.hit_dice = ""
        self.weapons = {} # {wpn1:[atk bonus, damage],wpn2:[atk bonus, damage],...}
        